constants:
  emotion_labels:
  - Ira
  - Miedo
  - Tristeza
  - "Alegr\xEDa"
  - Confianza
  - Sorpresa
data_paths:
  emotion_corpus_local: ./data/emotion_corpus_es.csv
model_params:
  cognitive_tutor:
    random_state: 42
  emotion_classifier:
    experimental_pipeline:
      cv_folds: 3
    model_name: dccuchile/bert-base-spanish-wwm-cased
    training_params:
      learning_rate: 2e-5
      logging_steps: 500
      num_train_epochs: 1
      per_device_train_batch_size: 16
      report_to: none
model_paths:
  emotion_classifier: ./saved_models/emotion_classifier
