# ===========================================================
# CONFIGURACIÓN DEL TUTOR COGNITIVO-AFECTIVO 
# ===========================================================

# --- Rutas de los Archivos ---
data_paths:
  # Ruta al archivo de datos crudos (leído por data_processing.py)
  raw_data: '/content/drive/MyDrive/Tesis Doctoral - CAFFETTI/base_estudio_discapacidad_2018.csv'
  
  # Rutas a los archivos generados (escritos por data_processing.py y leídos por otros scripts)
  demo_profiles: 'data/demo_profiles.csv'
  cognitive_training_data: 'data/cognitive_profiles.csv'

model_paths:
  emotion_classifier: 'saved_models/emotion_classifier'
  cognitive_tutor: 'saved_models/cognitive_tutor.joblib'

# --- Configuración de MLflow ---
mlflow:
  experiment_name: "Tutor Cognitivo-Afectivo Tesis"
  tracking_uri: "mlruns"

# --- Hiperparámetros y Configuración de los Modelos ---
model_params:
  emotion_classifier:
    model_name: 'dccuchile/bert-base-spanish-wwm-uncased'
    data_augmentation:
      use_back_translation: true
    early_stopping_patience: 2
    training_params:
      num_train_epochs: 3
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      warmup_steps: 500
      weight_decay: 0.01
      logging_dir: './logs'
      logging_steps: 10
      learning_rate: "2e-5"
      evaluation_strategy: "epoch"
      save_strategy: "epoch"
      metric_for_best_model: "f1_macro"

  cognitive_tutor:
    random_state: 42
    n_estimators: 100
    max_depth: 5
    min_samples_leaf: 10

# --- Constantes del Sistema ---
constants:
  emotion_labels:
    - "Alegría"
    - "Tristeza"
    - "Ira"
    - "Miedo"
    - "Sorpresa"
    - "Confianza"
    - "Anticipación"

  negative_emotions:
    - "Ira"
    - "Tristeza"
    - "Miedo"

# --- Reglas de Negocio y Umbrales ---

system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1
    min_recommendation_weight: 0.15

affective_rules:
  Ira:
    Com_Desafiado: 1.5
    Potencial_Latente: 1.3
  Miedo:
    Potencial_Latente: 1.6
    Cand_Nec_Sig: 1.4
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2
  Confianza:
    Prof_Subutil: 1.5
    Nav_Informal: 1.3
