# ==============================================================================
# CONFIGURACIÓN CENTRAL DEL PROYECTO - TUTOR COGNITIVO-AFECTIVO
# ==============================================================================
# Este archivo YAML sirve como la "fuente única de la verdad" para todos los
# parámetros, rutas y umbrales del sistema. Modificar este archivo permite
# experimentar y reconfigurar el pipeline sin alterar el código fuente.
# ==============================================================================
# ==============================================================================
# CONFIGURACIÓN CENTRAL DEL PROYECTO - TUTOR COGNITIVO-AFECTIVO
# ==============================================================================
# Versión final: Etiquetas de emoción SIN tilde y rutas de datos al Google DRIVE.
# ==============================================================================

affective_rules:
  Confianza:
    Nav_Informal: 1.3
    Prof_Subutil: 1.5
  Ira:
    Com_Desafiado: 1.5
    Potencial_Latente: 1.3
  Miedo:
    Cand_Nec_Sig: 1.4
    Potencial_Latente: 1.6
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2

constants:
  emotion_labels:
    - Alegria
    - Tristeza
    - Ira
    - Miedo
    - Sorpresa
    - Confianza
    - Anticipacion
  
  negative_emotions:
    - Ira
    - Tristeza
    - Miedo
  
  positive_emotions:
    - Alegria
    - Confianza
    - Anticipacion
    - Sorpresa

data_paths:

  raw_data: /content/drive/MyDrive/Tesis Doctoral - CAFFETTI/base_estudio_discapacidad_2018.csv
  cognitive_training_data: /content/drive/MyDrive/data/cognitive_profiles.csv
  demo_profiles: /content/drive/MyDrive/data/demo_profiles.csv

mlflow:
  experiment_name: Tutor Cognitivo-Afectivo Tesis
  tracking_uri: mlruns

model_params:
  cognitive_tutor:
    n_estimators: 100
    max_depth: 5
    min_samples_leaf: 10
    random_state: 42
  emotion_classifier:
    model_name: dccuchile/bert-base-spanish-wwm-uncased
    data_augmentation:
      use_back_translation: false # Desactivado, activese al necesitar aumento de corpus
    early_stopping_patience: 2
    training_params:
      num_train_epochs: 3
      learning_rate: 2.0e-5
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      weight_decay: 0.01
      warmup_steps: 500
      evaluation_strategy: epoch
      save_strategy: epoch
      metric_for_best_model: f1_macro

model_paths:
  cognitive_tutor: saved_models/cognitive_tutor.joblib
  emotion_classifier: saved_models/emotion_classifier

system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1
    min_recommendation_weight: 0.15

