affective_rules:
  Confianza:
    Nav_Informal: 1.3
    Prof_Subutil: 1.5
  Ira:
    Com_Desafiado: 1.5
    Potencial_Latente: 1.3
  Miedo:
    Cand_Nec_Sig: 1.4
    Potencial_Latente: 1.6
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2
constants:
  emotion_labels:
  - Alegria
  - Tristeza
  - Ira
  - Miedo
  - Sorpresa
  - Confianza
  - Anticipacion
  negative_emotions:
  - Ira
  - Tristeza
  - Miedo
  positive_emotions:
  - Alegria
  - Confianza
  - Anticipacion
  - Sorpresa
data_paths:
  cognitive_training_data: data/cognitive_profiles.csv
  demo_profiles: data/demo_profiles.csv
  raw_data: /content/drive/MyDrive/Tesis Doctoral - CAFFETTI/base_estudio_discapacidad_2018.csv
mlflow:
  experiment_name: Tutor Cognitivo-Afectivo Tesis
  tracking_uri: mlruns
model_params:
  cognitive_tutor:
    max_depth: 5
    min_samples_leaf: 10
    n_estimators: 100
    random_state: 42
  emotion_classifier:
    data_augmentation:
      use_back_translation: true
    early_stopping_patience: 2
    model_name: dccuchile/bert-base-spanish-wwm-uncased
    training_params:
      evaluation_strategy: epoch
      learning_rate: 2e-5
      logging_dir: ./logs
      logging_steps: 10
      metric_for_best_model: f1_macro
      num_train_epochs: 3
      per_device_eval_batch_size: 16
      per_device_train_batch_size: 16
      save_strategy: epoch
      warmup_steps: 500
      weight_decay: 0.01
model_paths:
  cognitive_tutor: saved_models/cognitive_tutor.joblib
  emotion_classifier: saved_models/emotion_classifier
system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1
    min_recommendation_weight: 0.15
