# ===========================================================
# CONFIGURACIÓN DEL TUTOR COGNITIVO-AFECTIVO
# ===========================================================
mlflow:
  experiment_name: "Tutor Cognitivo-Afectivo Tesis"
  tracking_uri: "mlruns"

data_paths:
  raw_data: 'data/raw/base_estudio_discapacidad_2018.csv'
  demo_profiles: 'data/raw/demo_profiles.csv'
  cognitive_training_data: 'data/raw/cognitive_profiles.csv'

model_paths:
  emotion_classifier: 'saved_models/emotion_classifier'
  cognitive_tutor: 'saved_models/cognitive_tutor.joblib'

model_params:
  emotion_classifier:
    model_name: 'dccuchile/bert-base-spanish-wwm-cased'
    data_augmentation:
      use_back_translation: true
    
    early_stopping_patience: 2
    training_params:
      num_train_epochs: 3
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      warmup_steps: 500
      weight_decay: 0.01
      logging_dir: './logs'
      logging_steps: 10
      learning_rate: "2e-5"
 
      evaluation_strategy: epoch
      save_strategy: epoch
      metric_for_best_model: f1_macro

  cognitive_tutor:
    random_state: 42
    max_depth: 5
    min_samples_leaf: 10

constants:
  emotion_labels:
    - "Alegría"
    - "Tristeza"
    - "Ira"
    - "Miedo"
    - "Sorpresa"
    - "Confianza"
    - "Anticipación"   # Nota: viene solo del corpus propio

  negative_emotions:
    - "Ira"
    - "Tristeza"
    - "Miedo"

system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1
    min_recommendation_weight: 0.15

affective_rules:
  Ira:
    Com_Desafiado: 1.5
    Potencial_Latente: 1.3
  Miedo:
    Potencial_Latente: 1.6
    Cand_Nec_Sig: 1.4
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2
  Confianza:
    Prof_Subutil: 1.5
    Nav_Informal: 1.3
