# ===========================================================
# CONFIGURACIÓN DEL TUTOR COGNITIVO-AFECTIVO
# ===========================================================

# --- 1. RUTAS DE ARCHIVOS ---
data_paths:
  demo_profiles: 'data/demo_profiles.csv'
  
model_paths:
  emotion_classifier: 'models/emotion_classifier'
  cognitive_tutor: 'models/cognitive_tutor.joblib'

# --- 2. PARÁMETROS DE LOS MODELOS ---
model_params:
  # --- Clasificador de Emociones ---
  emotion_classifier:
    model_name: 'dccuchile/bert-base-spanish-wwm-cased'
    training_params:
      num_train_epochs: 3
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      warmup_steps: 500
      weight_decay: 0.01
      logging_dir: './logs'
      logging_steps: 10
      learning_rate: "2e-5" # Mantener como string, se convierte a float en el script
    
    # --- ¡NUEVO! Sección para controlar el aumento de datos ---
    data_augmentation:
      use_back_translation: true # Poner en 'false' para entrenar sin aumento

  # --- Tutor Cognitivo (Árbol de Decisión) ---
  cognitive_tutor:
    random_state: 42
    max_depth: 5
    min_samples_leaf: 10

# --- 3. CONSTANTES Y REGLAS DEL SISTEMA ---
constants:
  emotion_labels:
    - "Alegría"
    - "Tristeza"
    - "Ira"
    - "Miedo"
    - "Sorpresa"
    - "Confianza"
    - "Anticipación"

# --- Sección para umbrales y reglas de negocio ---
system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1  # Probabilidad mínima para que una emoción active una regla
    min_recommendation_weight: 0.15 # Peso normalizado mínimo para mostrar la recomendación de un experto

# Reglas que modulan la activación de los expertos según la emoción
affective_rules:
  # Si la emoción es IRA...
  Ira:
    Com_Desafiado: 1.5  # ...aumenta la prioridad del Tutor de Interacción un 50%
    Potencial_Latente: 1.3 # ...aumenta la del Tutor de Bienestar un 30%
  
  # Si la emoción es MIEDO...
  Miedo:
    Potencial_Latente: 1.6
    Cand_Nec_Sig: 1.4
    
  # Si la emoción es TRISTEZA...
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2
    
  # Si la emoción es CONFIANZA...
  Confianza:
    Prof_Subutil: 1.5
    Nav_Informal: 1.3
