# ===========================================================
# CONFIGURACIÓN DEL TUTOR COGNITIVO-AFECTIVO
# ===========================================================

# --- 1. RUTAS DE ARCHIVOS ---
data_paths:
  demo_profiles: 'data/demo_profiles.csv'

  cognitive_training_data: 'data/cognitive_profiles.csv' # Ruta a los datos para entrenar el árbol de decisión

  
model_paths:
  emotion_classifier: 'models/emotion_classifier'
  cognitive_tutor: 'models/cognitive_tutor.joblib'

# --- 2. PARÁMETROS DE LOS MODELOS ---
model_params:
  emotion_classifier:
    model_name: 'dccuchile/bert-base-spanish-wwm-cased'
    training_params:
      num_train_epochs: 3
      per_device_train_batch_size: 16
      per_device_eval_batch_size: 16
      warmup_steps: 500
      weight_decay: 0.01
      logging_dir: './logs'
      logging_steps: 10
      learning_rate: "2e-5"
    data_augmentation:
      use_back_translation: true

  cognitive_tutor:
    random_state: 42
    max_depth: 5
    min_samples_leaf: 10

# --- 3. CONSTANTES Y REGLAS DEL SISTEMA ---
constants:
  emotion_labels:
    - "Alegría"
    - "Tristeza"
    - "Ira"
    - "Miedo"
    - "Sorpresa"
    - "Confianza"
    - "Anticipación"

  negative_emotions:
    - "Ira"
    - "Tristeza"
    - "Miedo"

system_thresholds:
  affective_engine:
    min_emotion_probability: 0.1
    min_recommendation_weight: 0.15

affective_rules:
  Ira:
    Com_Desafiado: 1.5
    Potencial_Latente: 1.3
  Miedo:
    Potencial_Latente: 1.6
    Cand_Nec_Sig: 1.4
  Tristeza:
    Potencial_Latente: 1.7
    Prof_Subutil: 1.2
  Confianza:
    Prof_Subutil: 1.5
    Nav_Informal: 1.3
